### ISSUE TITLE
Category Subscription

### ISSUE THREAD

**Issue by zminster** [thomascastleman/StabOverflow#1]
I'm thinking of the use case where I'm a student in HDS and I'm a CSP TA. I would want to subscribe to both CSP (for answering) and HDS (for reference), and get email triggers when new questions/answers are posted. There would need to be a db relation between user ids and category ids.

You might also consider the use case of subscribing to answers to specific questions. That should be the same as before, except a relation between user ids and question ids.

One last feature that might be nice: a "daily digest" where users get a summary of new questions either at midnight or first thing in the morning. This might be cool, since if the service gets popular the constant emails would get annoying :)

**Comment by thomascastleman** [comment]
Now this exists
